language: php

php:
  - 5.4
  - 5.5
  - 5.6

notifications:
  irc: "irc.freenode.org#molajo"
  email:
    - amystephen@gmail.com

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - phpunit  -c .dev/phpunit.xml --coverage-clover=coverage.clover
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
