language: php

php:
  - 5.3.3

services:
  - Redis
  - Memcached

notifications:
  irc: "irc.freenode.org#molajo"
  email: amystephen@gmail.com


before_script:
  - php .dev/travis-setup.php apc
  - composer update --dev
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - pyrus install pear/PHP_CodeSniffer
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install phpmd/PHP_PMD
  - phpenv rehash

script:
  - phpunit  -c .dev/phpunit.xml
